### ISSUE TITLE
Undefined Error in Internet Explorer - Unable to get property 'initialise'

### ISSUE THREAD

**Issue by mikejpoole** [tinesoft/ngx-cookieconsent#34]
### Bug Report or Feature Request
- [x] bug report (I searched the issues)

### CookieConsent and Library Versions?
- cookieconsent version: 3.1.0
- ngx-cookieconsent version: 2.0.0

### OS Version?
Windows 7

### Angular, Node and al Versions?
Angular CLI: 7.0.7
Node: 10.3.0
Angular: 7.0.4

### Repro steps
Open http://localhost:4200/ in Internet Explorer 10 or Edge

### The log given by the failure
Error: Operation failed. undefined : undefinedError: Uncaught (in promise): TypeError: Unable to get property 'initialise' of undefined or null reference
TypeError: Unable to get property 'initialise' of undefined or null reference
   at NgcCookieConsentService.prototype.init (http://localhost:4200/vendor.js:76077:13)
   at NgcCookieConsentService (http://localhost:4200/vendor.js:76024:9)
   at _createClass (http://localhost:4200/vendor.js:52257:13)
   at _createProviderInstance (http://localhost:4200/vendor.js:52227:13)
   at resolveNgModuleDep (http://localhost:4200/vendor.js:52190:17)
   at NgModuleRef_.prototype.get (http://localhost:4200/vendor.js:52899:9)
   at resolveDep (http://localhost:4200/vendor.js:53270:5)
   at createClass (http://localhost:4200/vendor.js:53142:13)
   at createDirectiveInstance (http://localhost:4200/vendor.js:53021:5)
   at createViewNodes (http://localhost:4200/vendor.js:54247:21)

### Desired functionality
To know what configuration settings we might have wrongly set.

Many thanks.

**Comment by mikejpoole** [comment]
Thanks for your reply Tine.

Sorry for not including the version numbers. They are:

- cookieconsent version: 3.1.0
- ngx-cookieconsent version: 2.0.0

I can confirm that `"node_modules/cookieconsent/build/cookieconsent.min.js",` exists in the `scripts` section of `angular.json`.

**Comment by mikejpoole** [comment]
Hi Tine, do you know why the cookie consent is causing an error in IE?

The offending line in vendor.js is:

```
            // Init the cookieconsent library with injected config
            this.cookieconsent.initialise(this.config, function (popup) { return _this.popupInstance = popup; });
```

So the problem seems to be that it does not recognise `this.cookieconsent`

**Comment by tinesoft** [comment]
Hi @mikejpoole ,

Everytime such an issue was reported to me, it was always due to the fact that dependent  `cookieconent` library was  somehow NOT bundled with the final application's files or NOT linked to in the **scripts** section of `index.html`?  

Can you inspect the final `vendor.js`, `index.html`  further and  confirm that you see references to content from `node_modules/cookieconsent/build/cookieconsent.min.js` ?

Of  course, if you have a repro project somewhere, i could help you debug more...

Cheers

**Comment by mikejpoole** [comment]
Thanks for your reply @tinesoft ,

`node_modules/ngx-cookieconsent/esm5/ngx-cookieconsent.es5.js` appears in `vendor.js` but `node_modules/cookieconsent/build/cookieconsent.min.js` does not.

`vendor.js` is in the scripts section of `index.html`.

The cookie warning displays in Chrome but throws and error in IE.

Have I missed a stage in the installation process?

Many thanks again.

**Comment by tinesoft** [comment]
Bingo!

As i suspected, the dependent `cookieconsent`  **is NOT bundled** in your final application files.
Only `ngx-cookieconsent` (THIS library) is. But the later, depends on the first  to do its job.

Can you post your **angular.json** file? what command do you run to build your app?

**Comment by mikejpoole** [comment]
Thanks @tinesoft 
The `angular.json` is:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "my-app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/my-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/icons/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/assets/thirdParty/css/prism.css",
              "node_modules/bootstrap/scss/bootstrap.scss",
              "node_modules/cookieconsent/build/cookieconsent.min.css",
              "node_modules/@fortawesome/fontawesome-pro/css/all.css",
              "src/assets/numbas/globalstyles.scss",
              "src/assets/numbas/globalstyles_override.scss",
				      "src/styles.scss"
            ],
            "scripts": [ 
				"node_modules/jquery/dist/jquery.min.js",
        "node_modules/bootstrap/dist/js/bootstrap.js",
        "node_modules/cookieconsent/build/cookieconsent.min.js",
        "src/assets/thirdParty/scripts/prism.js",
        "src/assets/thirdParty/scripts/selfassessment1_7.js",
        "src/assets/js/mediaPlayer.js",
        "src/assets/js/scholarStorage.js",
        "src/assets/js/scormPlayer.js",
        "src/assets/numbas/globalscripts.js",
        "src/assets/oldVle/scripts/hints.js",
        "src/assets/js/common.js",
        "src/assets/js/reports.js",
        "src/assets/js/student_reports.js",
        "src/assets/js/mockreportsdata.js"
			]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "my-app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "my-app:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "my-app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "my-app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "my-app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "my-app:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "my-app"
}
```

**Comment by tinesoft** [comment]
I don't see anything wrong with this config file...  

Are you using a custom builder ( ejected-version of webpack for i.e.)?

Have you tred out your app on different browsers/versions?

**Comment by mikejpoole** [comment]
Hi @tinesoft .

No we are not using a custom builder. We are just building it the Angular way inside VS Code.

The app loading screen works without any problem in Chrome and Firefox.

**Comment by tinesoft** [comment]
Hi  @mikejpoole 

The same configuration working fine on Chrome and FF, indicates this is not a config problem...
At this point, i'm afraid that without a **minimal repro project**, there is not much i can do... 😢 

Have you tried running the demo app https://tinesoft.github.io/ngx-cookieconsent/ on those same browers that are failing your app? That way, we could definitively eliminate a problem with the library itself.

**Comment by mikejpoole** [comment]
Hi @tinesoft 

I tried to load your demo app in Edge and IE10 and it also failed (although with different errors):

![mv-173 - cookie consent website in edge](https://user-images.githubusercontent.com/9463686/51971046-35428600-2470-11e9-9dfe-5e59248a4bed.PNG)

The console errors are:

-TypeError: Object doesn't support property or method 'find'
-TypeError: Object doesn't support property or method 'startsWith'
- TypeError: Object doesn't support property or method 'find'
- TypeError: Object doesn't support property or method 'from'

Two additional errors appear for IE9.

An error object is available for each if you would like it.

If I disable McAfee it still fails.

**Comment by mikejpoole** [comment]
Hi @tinesoft .

Did you notice that as well as the minor styling issues on the bar your webpage does not load in IE on Windows 7?

If the errors were just specific to my app then I would supply a min repo but as the Cookie Consent also breaks other IE sites in Windows 7 (including your own) is that not enough for you to replicate the errors? If the code does not work in IE for Windows 7 then I will need to use a different cookie product.

**Comment by mikejpoole** [comment]
Hi @tinesoft . Many thanks for all your help, it truly is appreciated. 

I would like to use your solution although you will understand that I have to know it is robust before investing more time into why it is failing on our installation. 

Do you have a rough timescale in mind for how long it would take you to address the issues and release an updated version?

**Comment by tinesoft** [comment]
As the cause remains uncertain and hardly reproductible, it is hard to give you a timescale...
Besides i have to work for a living too 😄, so i can only investigate on evenings and weekends.

But this is on  my top priority issue right now, so i'll keep you posted ASAP.

**Comment by tinesoft** [comment]
Hi,

Ok, i fixed the [demo app](https://tinesoft.github.io/ngx-cookieconsent) on IE. The problem was simply that some Angular [polyfills](https://github.com/tinesoft/ngx-cookieconsent/commit/bf687c0f0994c31d52006fbb9439950854271a83#diff-c52a8ae2bda19e36c1711f5cb83c4e0c) were missing to make the app work on IE (causing the  "`method not found`" error you mentionned).

As you can see, the cookie consent bar is working perfectly fine (styling included)...

So this seems specific to your app somehow... maybe missing IE polyfills as well?

**Comment by mikejpoole** [comment]
Thanks @tinesoft . 

Our error is a different one from the one I spotted on your site (all our IE polyfills were already enabled).

The error we are getting in IE on Windows 7 is 'Unable to get property 'initialise' of undefined or null reference'.

**Comment by tinesoft** [comment]
Hi Mike

With the demo app, we have proof that a basic Angular CLI project+ ngx-cookieconsent works on IE.
So one last time, unless i can get my hands on your code (or a repro project) there is no much i can do unfortunately... 😞 

I can be available this weekend  (time to detemine) to assist you via VS Code Share if interested. You can DM on Twitter (same pseudo) to arrange that.

Otherwise, i will be obliged to close this issue, until repro steps are provided.


Cheers

**Comment by mikejpoole** [comment]
Hi @tinesoft 

Thanks for your reply. It will take me some time to make a repo project. I will let you know once I have done so.

Many thanks,

Mike

**Comment by mikejpoole** [comment]
Hi @tinesoft . I have updated to the latest package (2.1.1) and the issue remains in IE on Windows 7.

**Comment by tinesoft** [comment]
Bummer 😕

**Comment by gigenthomas** [comment]
I am running into the same issue on Chrome 

Here's the Angular CLI 


`
Angular CLI: 8.3.28
Node: 12.18.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.28
@angular-devkit/build-angular     0.803.28
@angular-devkit/build-optimizer   0.803.28
@angular-devkit/build-webpack     0.803.28
@angular-devkit/core              8.3.28
@angular-devkit/schematics        8.3.28
@angular/cdk                      7.3.4
@angular/cli                      8.3.28
@angular/material                 7.3.4
@ngtools/webpack                  8.3.28
@schematics/angular               8.3.28
@schematics/update                0.803.28
rxjs                              6.6.0
typescript                        3.5.3
webpack                           4.39.2
`
Here's the relevant angular.json contents :

       "styles": [
              "node_modules/cookieconsent/build/cookieconsent.min.css",
               {
              
                "input": "src/main.scss"
              },

              {
                "input": "src/highlightjs/material-light.css"
              },
              {
                "input": "src/assets/pink-bluegrey.css",
                "lazy": true,
                "bundleName": "pink-bluegrey"
              },
              {
                "input": "src/assets/deeppurple-amber.css",
                "lazy": true,
                "bundleName": "deeppurple-amber"
              },
              {
                "input": "src/assets/indigo-pink.css",
                "lazy": true,
                "bundleName": "indigo-pink"
              },
              {
                "input": "src/assets/purple-green.css",
                "lazy": true,
                "bundleName": "purple-green"
              }
            ],
            "scripts": [
              "node_modules/cookieconsent/build/cookieconsent.min.js"
            ],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }


![cookie-consent-error](https://user-images.githubusercontent.com/3069429/92413222-f2dd3280-f103-11ea-8383-6e062b3bf53a.png)

**Comment by tinesoft** [comment]
Closed due to inactivity. Plus, death to IE! ^^
